_target_: ahcore.lit_module.AhCoreLightningModule

model:
  _target_: ahcore.models.new_unet.UNet
  _partial_: true
  num_input_ch: 3
  depth: 4
  num_initial_filters: 128
#  dropout_prob: 0.1

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 5e-4
  weight_decay: 1e-4
  betas:
    - 0.99
    - 0.9

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 100
