_target_: ahcore.lit_module.AhCoreLightningModule

model:
  _target_: ahcore.models.resnet50.Resnet50Classification
  _partial_: true

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0005

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
