[tool.black]
line-length = 120 # PyCharm line length
target-version = ['py39', 'py310']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.idea
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.pylint.messages_control]
disable = "W1203, C0415"

[tool.pylint.basic]
good-names="i,j,k,x,y,ex,Run,_"

[tool.pylint.'TYPECHECK']
generated-members=['numpy.*', 'torch.*', 'np.*', 'cv2.*']
ignored-modules=['pydantic', 'dlup']

[tool.pylint.format]
max-line-length = "120"

[tool.pylint.design]
max-args=20
max-branches=30
max-parents=15
