"""General module for datasets, samplers and lightning modules.

- Generic dataset generated by a manifest, which can handle classification, detection and segmentation.
- Samplers that for instance perform adaptive sampling, or define different weights per sample.
"""
