defaults:
  - model_summary.yaml
  - rich_progress_bar.yaml
  - write_h5_callback.yaml
  - write_tiff_callback.yaml
  - _self_

model_summary:
  max_depth: -1

write_h5_callback:
  max_queue_size: 100
  max_concurrent_writers: 4

write_tiff_callback:
  max_concurrent_writers: 4
