_target_: ahcore.losses.LossFactory
weights:
  - 1.0
  - 1.0
losses:
  - cross_entropy:
      _target_: ahcore.losses.cross_entropy
      _partial_: true
      label_smoothing: 0.08
      limit: -15.0
      topk: null
  - soft_dice:
      _target_: ahcore.losses.soft_dice
      _partial_: true
      ignore_index: 0
