_target_: ahcore.lit_module.AhCoreLightningModule

model:
  _target_: ahcore.models.feature_extractors.ibot_vit.iBOTViT
  architecture: "vit_base_pancan"
  encoder: "teacher"
  weights_path: null

optimizer: null

scheduler: null
