# @package _global_

# specify here default inference configuration
defaults:
  - _self_  # Means that any variables defined here will be overridden by possible subconfigs below
  - data_description: ???
  - datamodule: dataset.yaml
  - pre_transform: ???
  - augmentations: ???
  - task: segmentation_inference.yaml
  - logger: null
  - lit_module: ???
  - callbacks: inference.yaml
  - trainer: default.yaml
  - hydra: default.yaml  # if we want to setup different hydra logging dirs / color log
  - paths: default.yaml
  - machine_settings: example.yaml

  # experiment configs allow for version control of specific configurations
  # e.g. specific hyperparameter searches or something
  - experiment: null

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

  # optional local config for user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: segmentation.yaml

# checkpoint path
ckpt_path: ???

# task name -- used for output directory path (or name it to a specific experiment if you'd like)
task_name: "inference"

# tags that can be found in mlflow to keep track of experiments
# note you cannot append in cli currently (perhaps in future)
tags: ["dev"]

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: False

# force tags to be entered (e.g. for running experiments):
enforce_tags: False

# seed for random number generators in pytorch, numpy and python.random
seed: 42
