_target_: ahcore.utils.vector_database.vector_lookup.perform_vector_lookup_multi
reduce_method: "mean_kmeans5"
ranker:
  _target_: pymilvus.WeightedRanker
  weights: [0.7,0.3,0.3,0.3,0.3,0.3]
search_radius: 0.7
annotated_region_overlap: 0.7
limit_results: 10000
range_filter: 1.
force_recompute_annotated_vectors: false
print_results: true
plot_results: false