_target_: ahcore.utils.vector_database.vector_lookup.perform_vector_lookup_single
search_radius: 0.7
annotated_region_overlap: 0.7
limit_results: 10000
range_filter: 1.0
force_recompute_annotated_vectors: false
print_results: true
plot_results: false