_target_: ahcore.transforms.augmentations.AugmentationFactory

# These transforms will be applied in order as a first step.
initial_transforms:
  - _target_: ahcore.transforms.augmentations.MeanStdNormalizer
    mean: [0.0, 0.0, 0.0]
    std: [1.0, 1.0, 1.0]

# [a, b] select between a and b random intensity transforms to apply.
# If True, will select all in a random order. If False, will apply all sequentially.
random_apply_intensity: false
random_apply_weights_intensity: null
intensity_augmentations:
  - _target_: ahcore.transforms.augmentations.HEDColorAugmentation
    p: 0.5
    scale_sigma: 0.2  # HED-light
    bias_sigma: 0.2   # HED-light
  # - _target_: kornia.augmentation.ColorJitter
  #   p: 0.5
  #   brightness: 0.05
  #   contrast: 0.05
  #   saturation: 0.05
  #   hue: 0.05
  - _target_: kornia.augmentation.RandomGrayscale
    p: 0.1
    rgb_weights: null
  - _target_: kornia.augmentation.RandomGaussianBlur
    p: 0.5
    kernel_size: [9, 9]
    sigma: [0.1, 1.5]

# [a, b] select between a and b random geometric transforms to apply.
# If True, will select all in a random order. If False, will apply all sequentially.
random_apply_geometric: false
random_apply_weights_geometric: null
geometric_augmentations:
    - _target_: kornia.augmentation.RandomHorizontalFlip
      p: 0.5
    - _target_: kornia.augmentation.RandomVerticalFlip
      p: 0.5
    # - _target_: kornia.augmentation.RandomAffine
    #   p: 0.75
    #   degrees: null  # sampled randomly from -degree to +degree
    #   scale: [.97, 1.03]
    #   translate: null  # This is given in percentages for x and y
    #   shear: null
    # - _target_: kornia.augmentation.RandomPerspective
    #   p: 0.1
    #   distortion_scale: 0.15

# These transforms are applied in order as a final step.
final_transforms:
  - _target_: ahcore.transforms.augmentations.CenterCrop
    size: ${data_description.inference_grid.tile_size}  # specify in data_description
