defaults:
  - prediction_h5_writer.yaml
  - prediction_tiff_writer.yaml
  - _self_

prediction_h5_writer:
  max_queue_size: 100
  max_concurrent_writers: 4
  limit_bounds: True

prediction_tiff_writer:
  max_concurrent_writers: 4